#:schema vendor/carthage-software/mago/schema.json
version = "1"
php-version = "8.1"

[source]
paths = ["bin", "src", "tests/Unit", "tests/Integration"]
includes = ["vendor"]
excludes = ["tests/Unit/**/Fixtures/**", "tests/Integration/Fixtures/**"]
